### ISSUE TITLE
How do you run it?

### ISSUE THREAD

**Issue by joon2real** [dtzdev/TTC-V2#1]
Whats the run command?

**Comment by dtzdev** [comment]
> Whats the run command?

**Method 1(easier, requires installing code editor):** 
use IDE like Jetbrains IntelliJ to run it.

**Method 2(code editor not required, but little bit more complicated):** 
1. Make sure you have [JDK](https://www.oracle.com/java/technologies/downloads/#jdk20-windows) installed. (Make sure its installed to PATH, so it works globally"
2. Compile the Java file in "src" directory using command `javac TTCV2.java`. This will generate a compiled java file named "TTCV2.class".
3. Run the Java program using command `java TTCV2`

If you need more help feel free to ask!
